{{ if .managedCluster.ocpImage }}
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: {{ include "ocpImage" . | indent 6 }}
spec:
  releaseImage: {{  .managedCluster.ocpImage }}
{{ end }}