apiVersion: v1
kind: Secret
metadata:
  name: {{ .managedCluster.name }}-pull-secret
  namespace: {{ .managedCluster.name }}
data:
  .dockerconfigjson: |-
{{ index .pullSecret.data ".dockerconfigjson" | indent 4 }}
type: kubernetes.io/dockerconfigjson