apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: auto-detect
    vendor: auto-detect
{{ if .kubeConfig }}
    autoImportRetry: "0"
{{ end }}
  name: {{ .managedClusterName }}
spec:
  hubAcceptsClient: true
