# Copyright Contributors to the Open Cluster Management project

managedClusterName: <cluster_name>
addons:
  applicationManager:
    enabled: true
    argocdCluster: false
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  version: 2.2.0
#Provide the kubeConfig yaml here if you want to automatically import the cluster.
kubeConfig: |-
  <Kubeconfig>
autoImportRetry: 5
token: <token>
server: <api_server_url>
  

