apiVersion: v1
kind: Secret
metadata:
  name: {{ .managedCluster.name }}-vsphere-certs
  namespace: {{ .managedCluster.name }}
data:
  .cacert: {{ .managedCluster.vsphere.cacertificate | b64enc }}
type: Opaque
